language: bash

addons:
  apt:
    packages:
      - bc
      - links

before_install:
  - curl -sOL https://raw.githubusercontent.com/aureliojargas/clitest/master/clitest
  - chmod +x clitest
  - mv clitest testador

script:
  - make lint
  - make test-core
  - ./testador/run internet_travis

notifications:
  email: false
